# Householder矩阵
## Householder矩阵的定义
> 如果$H=I-2\omega\omega^{T} ,\quad$其中，${\parallel \omega\parallel}_{2}=1$。则称$H$为Householder矩阵。

## Householder矩阵的性质
> - Householder矩阵是Hemiter矩阵
> - Householder矩阵是正交矩阵
> - 正交变换不改变向量的长度，即：$\forall x\in R^{n},\quad{\parallel Hx \parallel}_{2} = {\parallel x \parallel}_{2}$

## 定理1
> 设$x、y\in R^2$,且$ {\parallel x\parallel}_2={\parallel y\parallel}_2$，则$ \exists {\text{Householder矩阵}H}$，使得$ Hx
=y$


# 针对列向量的Householder正交变换


In [1]:
import numpy as np

In [2]:
x1 = np.array([1,3,4]).reshape((-1,1))#目标向量
## 生成相应的单位向量
e1 = np.zeros(x1.shape[0])
e1[0]=1
y1 = (-np.sign(x1[0])*np.linalg.norm(x1)*e1).reshape((-1,1))
# 计算rho
rho = 2 / (np.dot((y1 - x1).T, (y1 - x1)))
I= np.identity(x1.shape[0])
omega =y1-x1
H1 = I-rho * np.dot(omega,omega.T)

In [3]:
np.dot(H1,x1)

array([[-5.09901951e+00],
       [-4.44089210e-16],
       [-4.44089210e-16]])

In [26]:
x1 = np.array([1,3,4]).reshape((-1,1))#目标向量
x1_=x1[1:]
## 生成相应的单位向量
e1 = np.zeros(x1_.shape[0])
e1[0]=1
y1 = (-np.sign(x1_[0])*np.linalg.norm(x1_)*e1).reshape((-1,1))
# 计算rho
rho = 2 / (np.dot((y1 - x1_).T, (y1 - x1_)))
I= np.identity(x1.shape[0])
omega = np.concatenate((np.array([0]).reshape((-1,1)), y1-x1_))
H1 = I-rho * np.dot(omega,omega.T)

In [27]:
np.dot(H1,x1)

array([[ 1.0000000e+00],
       [-5.0000000e+00],
       [-4.4408921e-16]])

# 针对矩阵的Householder正交相似变换

In [23]:
A=np.array([[1,3,4],[3,1,2],[4,2,1]])#目标矩阵
n=A.shape[0]
matrix=[] #储存矩阵
HA=[]#储存变换后的向量
for i in range(n-2):
    x=A[:,i].reshape((-1,1))
    x_=x[i+1:].reshape((-1,1))
    ## 生成相应的单位向量
    e1 = np.zeros(x_.shape[0])
    e1[0]=1
    y = (-np.sign(x_[0])*np.linalg.norm(x_)*e1).reshape((-1,1))
    # 计算rho
    rho = 2 / (np.dot((y - x_).T, (y - x_)))
    I= np.identity(x1.shape[0])
    omega = np.concatenate((np.array([0]*(i+1)).reshape((-1,1)), y-x_))
    H = I-rho * np.dot(omega,omega.T)
    matrix.append(H)
    HA.append(np.dot(H,x))
HA_=np.column_stack(HA)#最终简约后的矩阵

# 改进后的针对矩阵的Householder正交相似变换
> 参考的是：黄云清老师的《数值分析方法》教材

In [38]:
A=np.array([[1,3,4],[3,1,2],[4,2,1]])#目标矩阵
n=A.shape[0]
matrix=[] #储存矩阵
HA=[]#储存变换后的向量
for i in range(n-2):
    x=A[:,i].reshape((-1,1))
    x_=x[i+1:].reshape((-1,1))
    eta=max(x_)
    if eta==0:
        matrix.append(np.identity(n))
        HA.append(x)
        contiue
    x_=x_ /eta
    sigma=np.sign(x_[0])*np.linalg.norm(x_)
    beta=sigma*(sigma+x_[0])
    x_[0]=x_[0]+sigma
    omega = np.concatenate((np.array([0]*(i+1)).reshape((-1,1)),x_))
    H = I-1/beta * np.dot(omega,omega.T)
    matrix.append(H)
    HA.append(np.dot(H,x))
HA_=np.column_stack(HA)#最终简约后的矩阵

In [39]:
HA_

array([[ 1.0000000e+00],
       [-5.0000000e+00],
       [-4.4408921e-16]])